package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CountryStdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStdAllPropertiesEquals(CountryStd expected, CountryStd actual) {
        assertCountryStdAutoGeneratedPropertiesEquals(expected, actual);
        assertCountryStdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStdAllUpdatablePropertiesEquals(CountryStd expected, CountryStd actual) {
        assertCountryStdUpdatableFieldsEquals(expected, actual);
        assertCountryStdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStdAutoGeneratedPropertiesEquals(CountryStd expected, CountryStd actual) {
        assertThat(expected)
            .as("Verify CountryStd auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStdUpdatableFieldsEquals(CountryStd expected, CountryStd actual) {
        assertThat(expected)
            .as("Verify CountryStd relevant properties")
            .satisfies(e -> assertThat(e.getRelType()).as("check relType").isEqualTo(actual.getRelType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryStdUpdatableRelationshipsEquals(CountryStd expected, CountryStd actual) {
        assertThat(expected)
            .as("Verify CountryStd relationships")
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()))
            .satisfies(e -> assertThat(e.getStd()).as("check std").isEqualTo(actual.getStd()));
    }
}
