package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CountryCertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryCertAllPropertiesEquals(CountryCert expected, CountryCert actual) {
        assertCountryCertAutoGeneratedPropertiesEquals(expected, actual);
        assertCountryCertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryCertAllUpdatablePropertiesEquals(CountryCert expected, CountryCert actual) {
        assertCountryCertUpdatableFieldsEquals(expected, actual);
        assertCountryCertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryCertAutoGeneratedPropertiesEquals(CountryCert expected, CountryCert actual) {
        assertThat(expected)
            .as("Verify CountryCert auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryCertUpdatableFieldsEquals(CountryCert expected, CountryCert actual) {
        assertThat(expected)
            .as("Verify CountryCert relevant properties")
            .satisfies(e -> assertThat(e.getRelType()).as("check relType").isEqualTo(actual.getRelType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryCertUpdatableRelationshipsEquals(CountryCert expected, CountryCert actual) {
        assertThat(expected)
            .as("Verify CountryCert relationships")
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()))
            .satisfies(e -> assertThat(e.getCerf()).as("check cerf").isEqualTo(actual.getCerf()));
    }
}
