package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MarkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkAllPropertiesEquals(Mark expected, Mark actual) {
        assertMarkAutoGeneratedPropertiesEquals(expected, actual);
        assertMarkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkAllUpdatablePropertiesEquals(Mark expected, Mark actual) {
        assertMarkUpdatableFieldsEquals(expected, actual);
        assertMarkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkAutoGeneratedPropertiesEquals(Mark expected, Mark actual) {
        assertThat(expected)
            .as("Verify Mark auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkUpdatableFieldsEquals(Mark expected, Mark actual) {
        assertThat(expected)
            .as("Verify Mark relevant properties")
            .satisfies(e -> assertThat(e.getMarkNo()).as("check markNo").isEqualTo(actual.getMarkNo()))
            .satisfies(e -> assertThat(e.getEnName()).as("check enName").isEqualTo(actual.getEnName()))
            .satisfies(e -> assertThat(e.getChName()).as("check chName").isEqualTo(actual.getChName()))
            .satisfies(e -> assertThat(e.getImg()).as("check img").isEqualTo(actual.getImg()))
            .satisfies(e -> assertThat(e.getImgContentType()).as("check img contenty type").isEqualTo(actual.getImgContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarkUpdatableRelationshipsEquals(Mark expected, Mark actual) {}
}
