package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProdStdAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStdAllPropertiesEquals(ProdStd expected, ProdStd actual) {
        assertProdStdAutoGeneratedPropertiesEquals(expected, actual);
        assertProdStdAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStdAllUpdatablePropertiesEquals(ProdStd expected, ProdStd actual) {
        assertProdStdUpdatableFieldsEquals(expected, actual);
        assertProdStdUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStdAutoGeneratedPropertiesEquals(ProdStd expected, ProdStd actual) {
        assertThat(expected)
            .as("Verify ProdStd auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStdUpdatableFieldsEquals(ProdStd expected, ProdStd actual) {
        assertThat(expected)
            .as("Verify ProdStd relevant properties")
            .satisfies(e -> assertThat(e.getRelType()).as("check relType").isEqualTo(actual.getRelType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStdUpdatableRelationshipsEquals(ProdStd expected, ProdStd actual) {
        assertThat(expected)
            .as("Verify ProdStd relationships")
            .satisfies(e -> assertThat(e.getProd()).as("check prod").isEqualTo(actual.getProd()))
            .satisfies(e -> assertThat(e.getStd()).as("check std").isEqualTo(actual.getStd()));
    }
}
