package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProdCountryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdCountryAllPropertiesEquals(ProdCountry expected, ProdCountry actual) {
        assertProdCountryAutoGeneratedPropertiesEquals(expected, actual);
        assertProdCountryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdCountryAllUpdatablePropertiesEquals(ProdCountry expected, ProdCountry actual) {
        assertProdCountryUpdatableFieldsEquals(expected, actual);
        assertProdCountryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdCountryAutoGeneratedPropertiesEquals(ProdCountry expected, ProdCountry actual) {
        assertThat(expected)
            .as("Verify ProdCountry auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdCountryUpdatableFieldsEquals(ProdCountry expected, ProdCountry actual) {
        assertThat(expected)
            .as("Verify ProdCountry relevant properties")
            .satisfies(e -> assertThat(e.getRelType()).as("check relType").isEqualTo(actual.getRelType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdCountryUpdatableRelationshipsEquals(ProdCountry expected, ProdCountry actual) {
        assertThat(expected)
            .as("Verify ProdCountry relationships")
            .satisfies(e -> assertThat(e.getProd()).as("check prod").isEqualTo(actual.getProd()))
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()));
    }
}
