package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProdStickerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStickerAllPropertiesEquals(ProdSticker expected, ProdSticker actual) {
        assertProdStickerAutoGeneratedPropertiesEquals(expected, actual);
        assertProdStickerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStickerAllUpdatablePropertiesEquals(ProdSticker expected, ProdSticker actual) {
        assertProdStickerUpdatableFieldsEquals(expected, actual);
        assertProdStickerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStickerAutoGeneratedPropertiesEquals(ProdSticker expected, ProdSticker actual) {
        assertThat(expected)
            .as("Verify ProdSticker auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStickerUpdatableFieldsEquals(ProdSticker expected, ProdSticker actual) {
        assertThat(expected)
            .as("Verify ProdSticker relevant properties")
            .satisfies(e -> assertThat(e.getRelType()).as("check relType").isEqualTo(actual.getRelType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProdStickerUpdatableRelationshipsEquals(ProdSticker expected, ProdSticker actual) {
        assertThat(expected)
            .as("Verify ProdSticker relationships")
            .satisfies(e -> assertThat(e.getProd()).as("check prod").isEqualTo(actual.getProd()))
            .satisfies(e -> assertThat(e.getSticker()).as("check sticker").isEqualTo(actual.getSticker()));
    }
}
