package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StickerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStickerAllPropertiesEquals(Sticker expected, Sticker actual) {
        assertStickerAutoGeneratedPropertiesEquals(expected, actual);
        assertStickerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStickerAllUpdatablePropertiesEquals(Sticker expected, Sticker actual) {
        assertStickerUpdatableFieldsEquals(expected, actual);
        assertStickerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStickerAutoGeneratedPropertiesEquals(Sticker expected, Sticker actual) {
        assertThat(expected)
            .as("Verify Sticker auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStickerUpdatableFieldsEquals(Sticker expected, Sticker actual) {
        assertThat(expected)
            .as("Verify Sticker relevant properties")
            .satisfies(e -> assertThat(e.getStickerNo()).as("check stickerNo").isEqualTo(actual.getStickerNo()))
            .satisfies(e -> assertThat(e.getImg()).as("check img").isEqualTo(actual.getImg()))
            .satisfies(e -> assertThat(e.getImgContentType()).as("check img contenty type").isEqualTo(actual.getImgContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStickerUpdatableRelationshipsEquals(Sticker expected, Sticker actual) {}
}
